### ISSUE TITLE
Could you open the pre-processed dataset?

### ISSUE THREAD

**Issue by zhuofeng** [cherise215/Cooperative_Training_and_Latent_Space_Data_Augmentation#1]
Hey,
I am running you code, and I will be very thankful if you open the pre-processed ACDC dataset to us.
Thank you!

**Comment by cherise215** [comment]
Hi, Zhuofeng, 

The ACDC dataset can be downloaded via https://www.creatis.insa-lyon.fr/Challenge/acdc/databasesTraining.html. Due to privacy issues, we are unable to directly share with you here. Please email chen.chen15@imperial.ac.uk after you have registered for the data use.  We can share it with you upon reasonable request. 

Thanks.
Chen
